const MSG_CHANGE = 'MSG_CHANGE'

// 登录
const POST_LOGIN = 'POST_LOGIN'
const GET_USERINFO='GET_USERINFO'
const GET_ARTICLE='GET_ARTICLE'
const WRITE_ARTICLE_DONE='WRITE_ARTICLE_DONE'
const GET_ARTICLE_CATES='GET_ARTICLE_CATES'
const GET_ARTICLE_INFO='GET_ARTICLE_INFO'
const WRITE_VACATION='WRITE_VACATION'
const GET_VACATION_LIST='GET_VACATION_LIST'
const LOGOUT_SUBMIT='LOGOUT_SUBMIT'


export default {
	POST_LOGIN,
	MSG_CHANGE,
	GET_USERINFO,
	GET_ARTICLE,
	WRITE_ARTICLE_DONE,
	GET_ARTICLE_CATES,
	GET_ARTICLE_INFO,
	WRITE_VACATION,
	GET_VACATION_LIST,
	LOGOUT_SUBMIT
}
